const List<Map<String, dynamic>> kMockOrigins = [
  {
    'Oid': 101,
    'OidStr': 'O_MOCK_101',
    'Oname': 'Steam Kingdom',
    'Osubtitle': 'Clockwork frontier',
    'Odescription': 'A city powered by steam and fragile alliances.',
    'Ocover': '',
    'Ocopycount': 2300,
    'Oconnectcount': 4400000,
    'Otags': ['steampunk', 'politics'],
    'Oupdated_time': '2026-05-09T12:00:00Z',
    'Oworld_view_image': '',
    'Omap_image': '',
    'worldviewId': 'wv_mock_steam',
    'launchWorldName': 'Steam Kingdom',
    'Ocharacters': [
      {
        'id': 'c_1',
        'name': 'Iris Vale',
        'identity': 'Inventor',
        'image': '',
        'intro': 'Builds machines that predict social unrest.',
        'Ochar_point': 'loc_hub',
      },
      {
        'id': 'c_2',
        'name': 'Marshal Crow',
        'identity': 'Guardian',
        'image': '',
        'intro': 'Maintains order around the rail gate.',
        'Ochar_point': 'loc_gate',
      },
    ],
    'Omap_points': [
      {
        'id': 'loc_hub',
        'x': 30.0,
        'y': 45.0,
        'label': 'Central Hub',
        'image': '',
      },
      {
        'id': 'loc_gate',
        'x': 70.0,
        'y': 35.0,
        'label': 'Rail Gate',
        'image': '',
      },
    ],
  },
];
