const String kMockV1Now = '2026-05-20T10:00:00Z';

const String kMockV1SteamSubtitle =
    'Clockwork frontier where inventors, rail guardians, and uneasy merchant houses keep the city balanced while pressure rises beneath the brass streets.';
const String kMockV1NeonSubtitle =
    'Rainy cyberpunk port where dock guilds auction stolen memories while rogue AIs whisper routes through the neon fog.';
const String kMockV1VerdantSubtitle =
    'Botanical magic school whose living halls grow new classrooms, secret doors, and dangerous wishes before morning roll call.';
const String kMockV1DustSubtitle =
    'Desert signal survival caravan chasing radio ghosts across glass dunes before the next sand tide buries every tower.';
const String kMockV1MoonlitSubtitle =
    'Cozy supernatural midnight shop where sleepless guests trade secrets, dreams, and unfinished regrets over impossible pie.';

const Map<String, dynamic> kMockV1User = {
  'uid': 'u_mock_001',
  'name': 'Mock User',
  'avatar': '',
  'bio': 'Local mock profile for debug builds.',
  'last_login_at': kMockV1Now,
  'create_at': '2026-05-01T08:00:00Z',
  'follower_cnt': 12,
  'following_cnt': 8,
  'friend_cnt': 3,
  'create_origin_cnt': 1,
  'launch_world_cnt': 1,
  'join_world_cnt': 1,
};

const Map<String, dynamic> kMockV1PeerUser = {
  'uid': 'u_mock_peer',
  'name': 'Penny Hardaway',
  'avatar': '',
  'bio': 'A debug peer user for relation and DM flows.',
  'last_login_at': kMockV1Now,
  'create_at': '2026-05-02T08:00:00Z',
  'follower_cnt': 20,
  'following_cnt': 16,
  'friend_cnt': 5,
  'create_origin_cnt': 2,
  'launch_world_cnt': 2,
  'join_world_cnt': 4,
};

const Map<String, dynamic> kMockV1SelfRelation = {
  'is_self': true,
  'is_followed': false,
  'i_followed': false,
  'followed_me': false,
  'is_friend': false,
  'follow_button_state': 'self',
  'can_send_dm': false,
  'dm_permission': 'self',
};

const Map<String, dynamic> kMockV1PeerRelation = {
  'target_user_id': 'u_mock_peer',
  'is_self': false,
  'is_followed': false,
  'i_followed': false,
  'followed_me': true,
  'is_friend': false,
  'follow_button_state': 'follow_back',
  'can_send_dm': true,
  'dm_permission': 'pingpong',
};

const Map<String, dynamic> kMockV1Origin = {
  'oid': 'o_mock_001',
  'status': 2,
  'version_num': 1,
  'name': 'Steam Kingdom',
  'cover': '',
  'display_subtitle': kMockV1SteamSubtitle,
  'world_view': 'A city powered by steam and fragile alliances.',
  'world_setting': 'Players negotiate with inventors and rail guardians.',
  'created_uid': 'u_mock_001',
  'created_user_name': 'Mock User',
  'created_at': '2026-05-10T08:00:00Z',
  'updated_at': kMockV1Now,
  'tags': ['steampunk', 'politics'],
  'copy_cnt': 2300,
  'connect_cnt': 4400000,
  'discuss_cnt': 1250,
  'character_cnt': 3200,
  'location_cnt': 1800,
  'start_time': 'Day 1 08:00',
  'tick_duration_days': 30,
};

const List<Map<String, dynamic>> kMockV1Origins = [
  kMockV1Origin,
  {
    'oid': 'o_mock_002',
    'status': 2,
    'version_num': 3,
    'name': 'Neon Harbor',
    'cover': '',
    'display_subtitle': kMockV1NeonSubtitle,
    'world_view': 'A vertical port city where memory chips are traded at dusk.',
    'world_setting': 'Players broker deals between dock guilds and rogue AIs.',
    'created_uid': 'u_mock_peer',
    'created_user_name': 'Penny Hardaway',
    'created_at': '2026-05-08T08:30:00Z',
    'updated_at': '2026-05-19T11:20:00Z',
    'tags': ['cyberpunk', 'mystery'],
    'copy_cnt': 18500,
    'connect_cnt': 2500000000,
    'discuss_cnt': 4200,
    'character_cnt': 9800,
    'location_cnt': 6200,
    'start_time': 'Night 1 21:00',
    'tick_duration_days': 14,
  },
  {
    'oid': 'o_mock_003',
    'status': 1,
    'version_num': 1,
    'name': 'Verdant Academy',
    'cover': '',
    'display_subtitle': kMockV1VerdantSubtitle,
    'world_view':
        'A living campus grows new rooms according to student wishes.',
    'world_setting': 'Players discover why the oldest greenhouse is locked.',
    'created_uid': 'u_mock_001',
    'created_user_name': 'Mock User',
    'created_at': '2026-05-06T09:00:00Z',
    'updated_at': '2026-05-18T15:40:00Z',
    'tags': ['fantasy', 'academy'],
    'copy_cnt': 240000,
    'connect_cnt': 7300000000000,
    'discuss_cnt': 6800,
    'character_cnt': 1500,
    'location_cnt': 4100,
    'start_time': 'Spring 1 07:30',
    'tick_duration_days': 21,
  },
  {
    'oid': 'o_mock_004',
    'status': 2,
    'version_num': 2,
    'name': 'Dust Radio',
    'cover': '',
    'display_subtitle': kMockV1DustSubtitle,
    'world_view': 'A caravan follows radio ghosts through a glass desert.',
    'world_setting': 'Players tune signal towers before the next sand tide.',
    'created_uid': 'u_mock_peer',
    'created_user_name': 'Penny Hardaway',
    'created_at': '2026-05-04T10:10:00Z',
    'updated_at': '2026-05-17T12:10:00Z',
    'tags': ['survival', 'roadtrip'],
    'copy_cnt': 4400000,
    'connect_cnt': 980000000,
    'discuss_cnt': 12000,
    'character_cnt': 7300,
    'location_cnt': 8400,
    'start_time': 'Dawn 1 05:50',
    'tick_duration_days': 10,
  },
  {
    'oid': 'o_mock_005',
    'status': 2,
    'version_num': 1,
    'name': 'Moonlit Diner',
    'cover': '',
    'display_subtitle': kMockV1MoonlitSubtitle,
    'world_view': 'A diner appears only to people who cannot sleep.',
    'world_setting':
        'Players serve guests while learning what keeps them awake.',
    'created_uid': 'u_mock_001',
    'created_user_name': 'Mock User',
    'created_at': '2026-05-03T06:00:00Z',
    'updated_at': '2026-05-16T23:30:00Z',
    'tags': ['slice-of-life', 'supernatural'],
    'copy_cnt': 12300000,
    'connect_cnt': 18500000,
    'discuss_cnt': 9100,
    'character_cnt': 5200,
    'location_cnt': 3600,
    'start_time': 'Midnight 1 00:00',
    'tick_duration_days': 7,
  },
];

const List<Map<String, dynamic>> kMockV1Characters = [
  {
    'type': 'ai',
    'status': 10,
    'player_uid': '',
    'character_id': 'c_mock_iris',
    'name': 'Iris Vale',
    'identity': 'Inventor',
    'tagline': 'Predicts unrest through machines.',
    'description': 'Builds devices that turn city rumors into forecasts.',
    'goal': 'Keep the Central Hub stable.',
    'avatar': '',
    'location_id': 'loc_hub',
  },
  {
    'type': 'ai',
    'status': 10,
    'player_uid': '',
    'character_id': 'c_mock_crow',
    'name': 'Marshal Crow',
    'identity': 'Guardian',
    'tagline': 'Keeps order around the rail gate.',
    'description': 'Protects the line between commerce and chaos.',
    'goal': 'Prevent sabotage at the Rail Gate.',
    'avatar': '',
    'location_id': 'loc_gate',
  },
];

const Map<String, dynamic> kMockV1Metric = {
  'mode': 'quantitative',
  'label': 'City Pressure',
  'unit': 'pressure',
  'range': [0, 100],
  'default': 50,
};

const List<Map<String, dynamic>> kMockV1Locations = [
  {
    'location_id': 'loc_hub',
    'name': 'Central Hub',
    'description': 'A loud station filled with brass pipes and gossip.',
    'image': '',
    'x_percent': 30.0,
    'y_percent': 45.0,
  },
  {
    'location_id': 'loc_gate',
    'name': 'Rail Gate',
    'description': 'The armored gate that controls access to the old rails.',
    'image': '',
    'x_percent': 70.0,
    'y_percent': 35.0,
  },
];

const List<Map<String, dynamic>> kMockV1Events = [
  {'content': 'Steam pressure spikes near the Central Hub.'},
  {'content': 'A suspicious crate arrives at the Rail Gate.'},
];

const Map<String, dynamic> kMockV1World = {
  'oid': 'o_mock_001',
  'origin_version_num': 1,
  'origin_version_create_at': '2026-05-10T08:00:00Z',
  'wid': 'w_mock_001',
  'status': 1,
  'is_join': 1,
  'apply_status': 'success',
  'name': 'Steam Kingdom Live',
  'cover': '',
  'display_subtitle': kMockV1SteamSubtitle,
  'world_view': 'A city powered by steam and fragile alliances.',
  'world_setting': 'Players negotiate with inventors and rail guardians.',
  'created_uid': 'u_mock_001',
  'created_user_name': 'Mock User',
  'owner_uid': 'u_mock_001',
  'owner_name': 'Mock User',
  'created_at': '2026-05-11T08:00:00Z',
  'updated_at': kMockV1Now,
  'last_progress_at': kMockV1Now,
  'last_progress_summary': 'The city reacts to a new player message.',
  'tags': ['steampunk', 'politics'],
  'tick_cnt': 1240,
  'connect_cnt': 3200,
  'ai_character_cnt': 4200,
  'player_cnt': 3100,
  'location_cnt': 2500,
};

const List<Map<String, dynamic>> kMockV1Worlds = [
  kMockV1World,
  {
    'oid': 'o_mock_002',
    'origin_version_num': 3,
    'origin_version_create_at': '2026-05-08T08:30:00Z',
    'wid': 'w_mock_002',
    'status': 1,
    'is_join': 1,
    'apply_status': 'success',
    'name': 'Neon Harbor Night Shift',
    'cover': '',
    'display_subtitle': kMockV1NeonSubtitle,
    'world_view': 'A vertical port city where memory chips are traded at dusk.',
    'world_setting': 'Players broker deals between dock guilds and rogue AIs.',
    'created_uid': 'u_mock_peer',
    'created_user_name': 'Penny Hardaway',
    'owner_uid': 'u_mock_peer',
    'owner_name': 'Penny Hardaway',
    'created_at': '2026-05-12T09:00:00Z',
    'updated_at': '2026-05-19T11:20:00Z',
    'last_progress_at': '2026-05-19T11:20:00Z',
    'last_progress_summary': 'The crew found a corrupted memory manifest.',
    'tags': ['cyberpunk', 'mystery'],
    'tick_cnt': 18500,
    'connect_cnt': 4400000,
    'ai_character_cnt': 9800,
    'player_cnt': 7300,
    'location_cnt': 6200,
  },
  {
    'oid': 'o_mock_003',
    'origin_version_num': 1,
    'origin_version_create_at': '2026-05-06T09:00:00Z',
    'wid': 'w_mock_003',
    'status': 1,
    'is_join': 0,
    'apply_status': 'none',
    'name': 'Verdant Academy Term One',
    'cover': '',
    'display_subtitle': kMockV1VerdantSubtitle,
    'world_view':
        'A living campus grows new rooms according to student wishes.',
    'world_setting': 'Players discover why the oldest greenhouse is locked.',
    'created_uid': 'u_mock_001',
    'created_user_name': 'Mock User',
    'owner_uid': 'u_mock_001',
    'owner_name': 'Mock User',
    'created_at': '2026-05-13T07:00:00Z',
    'updated_at': '2026-05-18T15:40:00Z',
    'last_progress_at': '2026-05-18T15:40:00Z',
    'last_progress_summary': 'A hallway bloomed into a new classroom.',
    'tags': ['fantasy', 'academy'],
    'tick_cnt': 240000,
    'connect_cnt': 2500000000,
    'ai_character_cnt': 1500,
    'player_cnt': 4100,
    'location_cnt': 5200,
  },
  {
    'oid': 'o_mock_004',
    'origin_version_num': 2,
    'origin_version_create_at': '2026-05-04T10:10:00Z',
    'wid': 'w_mock_004',
    'status': 1,
    'is_join': 1,
    'apply_status': 'success',
    'name': 'Dust Radio Caravan',
    'cover': '',
    'display_subtitle': kMockV1DustSubtitle,
    'world_view': 'A caravan follows radio ghosts through a glass desert.',
    'world_setting': 'Players tune signal towers before the next sand tide.',
    'created_uid': 'u_mock_peer',
    'created_user_name': 'Penny Hardaway',
    'owner_uid': 'u_mock_peer',
    'owner_name': 'Penny Hardaway',
    'created_at': '2026-05-14T05:50:00Z',
    'updated_at': '2026-05-17T12:10:00Z',
    'last_progress_at': '2026-05-17T12:10:00Z',
    'last_progress_summary': 'A signal tower answered with a child voice.',
    'tags': ['survival', 'roadtrip'],
    'tick_cnt': 4400000,
    'connect_cnt': 980000000,
    'ai_character_cnt': 7300,
    'player_cnt': 8400,
    'location_cnt': 6900,
  },
  {
    'oid': 'o_mock_005',
    'origin_version_num': 1,
    'origin_version_create_at': '2026-05-03T06:00:00Z',
    'wid': 'w_mock_005',
    'status': 1,
    'is_join': 1,
    'apply_status': 'success',
    'name': 'Moonlit Diner Regulars',
    'cover': '',
    'display_subtitle': kMockV1MoonlitSubtitle,
    'world_view': 'A diner appears only to people who cannot sleep.',
    'world_setting':
        'Players serve guests while learning what keeps them awake.',
    'created_uid': 'u_mock_001',
    'created_user_name': 'Mock User',
    'owner_uid': 'u_mock_001',
    'owner_name': 'Mock User',
    'created_at': '2026-05-15T00:00:00Z',
    'updated_at': '2026-05-16T23:30:00Z',
    'last_progress_at': '2026-05-16T23:30:00Z',
    'last_progress_summary': 'A customer paid with a forgotten dream.',
    'tags': ['slice-of-life', 'supernatural'],
    'tick_cnt': 12300000,
    'connect_cnt': 18500000,
    'ai_character_cnt': 5200,
    'player_cnt': 3600,
    'location_cnt': 4500,
  },
];

const List<Map<String, dynamic>> kMockV1Ticks = [
  {
    'tick_index': 3,
    'created_at': kMockV1Now,
    'summary': 'Iris warns that pressure is rising.',
  },
];

const List<Map<String, dynamic>> kMockV1Notifications = [
  {
    'id': 12,
    'category': 'system',
    'kind': 'world_join_request',
    'wid': 'w_mock_001',
    'owner_uid': 'u_mock_001',
    'apply_uid': 'u_mock_peer',
    'apply_user_name': 'Penny Hardaway',
    'apply_user_avatar': '',
    'message': 'Penny wants to join Steam Kingdom Live.',
    'status': 'pending',
    'is_read': false,
    'created_at': kMockV1Now,
  },
  {
    'id': 13,
    'category': 'follower',
    'kind': 'new_follower',
    'uid': 'u_mock_peer',
    'message': 'Penny Hardaway started following you.',
    'is_read': false,
    'created_at': '2026-05-20T09:50:00Z',
  },
  {
    'id': 14,
    'category': 'comment',
    'kind': 'origin_comment',
    'oid': 'o_mock_001',
    'uid': 'u_mock_peer',
    'message': 'Penny commented: "Love this world setting!"',
    'is_read': false,
    'created_at': '2026-05-20T09:40:00Z',
  },
];

const List<Map<String, dynamic>> kMockV1DmMessages = [
  {
    'message_id': 'dm_msg_001',
    'conversation_id': 'dm_conv_001',
    'seq': 1,
    'sender_uid': 'u_mock_peer',
    'message_type': 'text',
    'content': 'Ready to test the local mock service?',
    'create_time': '2026-05-20T09:55:00Z',
  },
  {
    'message_id': 'dm_msg_002',
    'conversation_id': 'dm_conv_001',
    'seq': 2,
    'sender_uid': 'u_mock_001',
    'message_type': 'text',
    'content': 'Yes, keep everything deterministic.',
    'create_time': '2026-05-20T09:56:00Z',
  },
];

const Map<String, dynamic> kMockV1DmConversation = {
  'conversation_id': 'dm_conv_001',
  'peer_name': 'Penny Hardaway',
  'peer_uid': 'u_mock_peer',
  'peer_avatar': '',
  'last_message_text': 'Yes, keep everything deterministic.',
  'last_message_at': '2026-05-20T09:56:00Z',
  'last_message_sender_uid': 'u_mock_001',
  'unread_cnt': 0,
  'dm_permission': 'unlimited',
};

const List<Map<String, dynamic>> kMockV1DiscussPosts = [
  {
    'post_id': 'p_mock_001',
    'uid': 'u_mock_peer',
    'user_name': 'Penny Hardaway',
    'user_avatar': '',
    'create_at': 1789783200,
    'content': 'The Central Hub feels different after the last tick.',
    'images': <String>[],
    'liked_by_me': false,
    'like_cnt': 3,
    'reply_cnt': 1,
    'best_tick_cnt': 3,
    'best_wid': 'w_mock_001',
  },
];

const List<Map<String, dynamic>> kMockV1DiscussReplies = [
  {
    'post_id': 'p_mock_reply_001',
    'uid': 'u_mock_001',
    'user_name': 'Mock User',
    'user_avatar': '',
    'create_at': 1789783300,
    'content': 'That is intentional mock data for debug.',
    'images': <String>[],
    'liked_by_me': false,
    'like_cnt': 0,
    'reply_cnt': 0,
    'best_tick_cnt': 0,
    'best_wid': 'w_mock_001',
  },
];
